### ISSUE TITLE
Fix building-type and name field

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-default-config#39]
Since we are now integrating the default config into CoMapeo and validating it given schemas in [mapeo-schema](https://github.com/digidem/mapeo-schema/), there are some fields with incorrect types. Mainly I've found two (which are the only ones that don't pass schema validation):
1. name -> the `type` property as a value of `localized` but on mapeo-schema we don't accept that value for that property ([see](https://github.com/digidem/mapeo-schema/blob/481a5ef7203875760aea782e1da804b0625c1a67/schema/field/v2.json#L17))
2. building-type 
    1. the `options` field is formated as a list of `string`, where is should actually be a list of `{label:string, value: any}` (so, an object with a label and a value, [see](https://github.com/digidem/mapeo-schema/blob/481a5ef7203875760aea782e1da804b0625c1a67/schema/field/v2.json#L47))
    2. the `type` property as a value of `select-one` when it should be `selectOne`
    3. missing `label` property which is required

The main solution for this would be to change this fields so that they pass validation, the second would be to change the schemas so that the fields are valid. I'm more inclined to the first option, but there maybe reasons that I don't know for maintaining this fields as is...

Also, there may be other invalid fields or presets, I'm still patching these errors live so that I can see what is missing...

**Comment by gmaclennan** [comment]
> Since we are now integrating the default config into CoMapeo and validating it given schemas in [mapeo-schema](https://github.com/digidem/mapeo-schema/), there are some fields with incorrect types. Mainly I've found two (which are the only ones that don't pass schema validation):
> 
> 1. name -> the `type` property as a value of `localized` but on mapeo-schema we don't accept that value for that property ([see](https://github.com/digidem/mapeo-schema/blob/481a5ef7203875760aea782e1da804b0625c1a67/schema/field/v2.json#L17))

I think since we don't support a localizable fields in the UI at the moment, then we should convert these to a field type of `text`. (this is a field type supported by iD editor, and follows a common standard in OSM of adding localized fields appended with a `:${LANG_CODE}`. In the iD interface you can add multiple translations for a localizable field, e.g. for the [city of london](https://www.openstreetmap.org/relation/65606). We can look at adding this feature at a later stage, at which point we can add this to the schema)

> 2. building-type
>    
>    1. the `options` field is formated as a list of `string`, where is should actually be a list of `{label:string, value: any}` (so, an object with a label and a value, [see](https://github.com/digidem/mapeo-schema/blob/481a5ef7203875760aea782e1da804b0625c1a67/schema/field/v2.json#L47))

We should update the default config to the label and value format - this was a legacy format we used to support but have now dropped.

>    2. the `type` property as a value of `select-one` when it should be `selectOne`

I think ok to change the default config to use camelCase. I initially wondered if we had it for compat with [iD Editor field types](https://github.com/ideditor/schema-builder?tab=readme-ov-file#type), but iD does not have select one and select multiple anyway. camelCase, while not everyone's preference, is what we are using everywhere so we should keep it as such for consistency.

>    3. missing `label` property which is required

We should add this to the default config where it is missing.
